apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.25.1
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
