apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.15.11
  values:
    alertmanager:
      enabled: false
    coreDns:
      service:
        selector:
          k8s-app: coredns
    grafana:
      admin:
        existingSecret: admin-user
      envFromSecret: envvars
      grafana.ini:
        server:
          root_url: https://grafana.9ka.nl
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: false
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
        auth.generic_oauth:
          enabled: true
          name: 9ka
          allow_sign_up: true
          client_id: grafana
          scopes: openid profile email
          auth_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/auth
          token_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/token
          api_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/userinfo
          allowed_domains: kippendief.biz
        auth:
          signout_redirect_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/logout
        users:
          allow_org_create: false
          auto_assign_org: true
          auto_assign_org_role: Admin
        security:
          allow_embedding: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
#          nginx.ingress.kubernetes.io/whitelist-source-range: 185.227.75.212,94.103.16.181,217.114.100.73,217.114.98.148,172.21.40.0/21,2001:1540:802:6::/64
#          ingress.kubernetes.io/custom-frame-options-value: barbuda.mgt.virtu.nl
        enabled: true
        hosts:
        - grafana.9ka.nl
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.9ka.nl
      plugins:
      - fetzerch-sunandmoon-datasource
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/whitelist-source-range: 185.227.75.212,172.21.40.0/21,2001:1540:802:6::/64
        enabled: true
        hosts:
        - prometheus.9ka.nl
        tls:
        - secretName: prometheus-tls
          hosts:
          - prometheus.9ka.nl
      prometheusSpec:
        retention: 2w
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: sas
              resources:
                requests:
                  storage: 10Gi
  valuesFrom:
  - secretKeyRef:
      name: helm-secrets
