apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-user
  namespace: prometheus-operator
spec:
  encryptedData:
    admin-password: AgCzALiqEXJ4ZZm+UNJwPNufqWH69nTEPBjaonLZwlJ8sutLI3SetxYQJv6hbp+9zVVI0fnwGNb0HMRnHym2qU43jnZ3CpGTSZ3AsS86zYUAQTpg5e6O4J2RMeBkAddsmd2ioq0OxQ2mxG6oaI8pxw0G/Jwlkou78TSaQxMe6ephwryi9ihz7HfM1nvbS4gaWvuth/NPJOn/NElPe+YSwx6AiuDmZWz3ljd0H0u7R0k2DcSZOI37k0L2zzUjKqP+w/au1R8Oa5NdMVcVmEr168zVcNzExpcfr0qWEa3SuXLNATlbq4SaBu0H60bgs4zjOK+LiQb2vN+NvLEZLin9sHGc2pMKpZpT1dKKLyke3ArwTsiVQHtFyEH4gFWG2n6BuWNRNiiHIXI44eawtU0TytKA9Ld2rIzfZyz/KM8Jw1vSEqkXCW05fzJrpbRJKma9C+YwkEJW9Bge+JyrMJq/13s2ihIkIKnKQkbkYzhBz7jk2a2jEsdEPDkBWU6KKeatrpUdJkU8KbqkqYguK38sP3Fo4cyXswNqCagWJyP5PbuyVfflniJYWQ3XURY1rtaGr3oazWgMdZu70uQ4jV04w7NvQiF6trcIuosDsIr4BEgIX8dhGyMv5G7kAtJ+sptlFQNevj7/SD0xXhl9XjK2ARNbALzdXumlM1dFT7PqsTqVfT/95ffVY87dZ2iI9P07OMsvnlcIdQcwLA==
    admin-user: AgB28BP+kWbksVXI4yQSkrHgMvCKjw0sUHjyVNVxHQ027RqOm+Nmx/RUnlX+0rOLilTvBvHlGU8/OQplyHzcEQRRQmAY7+ZojtdQSAWM18B1ePbAIAe0+/InVbSSFWDg7tsodTRh7Iyzcdt/Si5xU8X7MafGclUuAeVb4XvxrA5DuqyZaTEm9vvEqBDkzeHaH4Cc/l1jbV3CvRsAV6x8gfa1jZAYy6AAcje2rCTC7C1ZNpyaM8WXconi0/zW+X6Z1ch7VhUTv8HZRJN3L9rHm5PLkDsalgz0omPvphFRgHTRjLD+EEfXYCgkZ7ZMFVljkEqHpX2eGZyqUpu8xTg0z3PtqcJp9tcCTLqRcMrsKjg479aIufRxuIhp40453Y7EA2q5Lfg6epvzVGVpLDqY9nbKw+dQAEmb4ytyVycduibDw6uorR8tgANGgoowzR6GGbBoNCUSs6flZ+ld8KXSrxDAclFJXj5hSFatmhjbP08F+IolA9rGI742F8mC3LZDvUKBDe5DVisqrOsExKlrtK+DlScUYOPrnvbhx1gkROHjd0hHlDbr4S2ltWu4KixfGN4CBZgC9+AHcLmc0UB6ZlYxx8AZuymK4mBwwLbZrtWKzL+To/zQO0pG8MXhXrQClY+nEHSm6eG83DZod5ws4meFlVagO+20WzW/UcIFrMqFH9CC9MJQK6vGWXUuEp+CX50rtdSX1w==
  template:
    metadata:
      creationTimestamp: null
      name: admin-user
      namespace: prometheus-operator
    type: Opaque

