apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgDN1A22gpb107F3m2D9eqE+bRNfjpEug1CazlNwQIE9TaSRouti/558he08+eddRgSfzd/STXHsjExzSAQU1T3ZJW7uqhp4KGJX/caa9+fIvA4k5Q6LFGXymZmmRnC8rD5BimfJECY99LQYat85QLj7Fc6H6OH2qqxVywiTK5IWVQu7vTZjI4IDPfA0ARt4BmsdAF86UK2rzkMVizpCez5uOwX1ajK2R3AdlWPJIRpQnatvKjJyAP9TF8JcSPj8ybv6U2p5R8Uv4AjyEp6YZHRS7xFdl46N8nfbFTzaxgzvVoSBq3IDT4oEwTMLuTx8v2BMBFFiccSy6bErst9VFC980cNtpv6DyehtT/gadzXKLj10enmLc1dm+oRpgLabw9O+DH9dGw2NqRziBuCxKwvZAIDXNhExx2WL1QjYPkYjQkVDikk9oP46tgR4RLIxAQPsjReYpGNAIkEBIdVTDMX+nEjW52K5QfC9EPEil2sTNQbKJFu3Yl34U4lf7BjK/KjYQwHVFJabPx9Q+UYHGbry+7IE6pWEMlfFu6+0W/4i3rgBij7xczRfc8oPrTLVMqqN/NTd2N9e9QGPJkxsTQhERnNwF+5293yuqLKIh8+E6H1dF9uu7si88gtF0xpScvE+AFp/+8im/HcG0jMmi1vB/2NGUcus8Wg5fiY0ZJrq5I8Ok6TWU6sRaXLiWNCR5fFtfgMBjExQjy80gS5JujQh8+BTrZASH38HAYlK0VWlntksRIpY2lGhRrooqHfj5EQjbLl32rOI7qwbvJ1HzG8WL4linTFQmVmoWAByyVWHqBfl6Ehvh8AIuJ29ktj7DRQbtx0n1hb0IdCh/dI7rHXtBZLSOk4LI/yHlvW4u4Z2DQVIDczu
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: monitoring
status: {}

