---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-iioflux
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  influx-iioflux.yaml: |-
    apiVersion: 1
    datasources:
    - name: iioflux
      type: influxdb
      access: proxy
      url: http://influxdb.influxdb:8086/
      database: iioflux
      user: $INFLUX_USER
      secureJsonData:
        password: $INFLUX_PASSWORD
      editable: false
...
