---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-solar-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  solar.yaml: |-
    apiVersion: 1
    datasources:
    - name: solar
      type: influxdb
      access: proxy
      url: http://influxdb.influxdb:8086/
      database: solar
      user: $INFLUX_USER
      secureJsonData:
        password: $INFLUX_PASSWORD
      editable: false
...
