{
 "title": "Proxmox VE",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pve_qemu_ram_total) by (qemu)",
     "legendFormat": "{{qemu}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pve_qemu_cpu_usage) by (qemu)",
     "legendFormat": "{{qemu}}"
    }
   ]
  },
  {
   "title": "Net/in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pve_qemu_net_in[5m])) by (qemu)",
     "legendFormat": "{{qemu}}"
    }
   ]
  },
  {
   "title": "Net/out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pve_qemu_net_out[5m])) by (qemu)",
     "legendFormat": "{{qemu}}"
    }
   ]
  }
 ]
}