{
 "title": "PyNuts",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "District Heat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heat",
     "select": [
      [
       { "params": [ "t_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heat",
     "select": [
      [
       { "params": [ "t_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"energy\"), 1s) FROM \"heat\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt", "label": "power" }
   ],
   "targets": [
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"electricity_used_tariff_1\"), 1s) FROM \"power\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"electricity_used_tariff_2\"), 1s) FROM \"power\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity delivered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watt", "label": "power" }
   ],
   "targets": [
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"electricity_delivered_tariff_1\"), 1s) FROM \"power\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"electricity_delivered_tariff_2\"), 1s) FROM \"power\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "litreh" }
   ],
   "targets": [
    {
     "alias": "water",
     "groupBy": [
      { "params": [ "" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 3600 * non_negative_derivative(mean(\"volume\"), 1s) * COUNT(\"volume\") / COUNT(\"volume\") FROM \"water\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily electricity consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT difference(mean(\"electricity_used_tariff_1\"))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "electricity_used_tariff_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT difference(mean(\"electricity_used_tariff_1\"))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "electricity_used_tariff_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT (difference(mean(\"electricity_used_tariff_1\")) + difference(mean(\"electricity_used_tariff_2\")))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) tz('Europe/Amsterdam')",
     "select": [
      [
       { "params": [ "electricity_used_tariff_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    }
   ]
  },
  {
   "title": "Daily electricity delivery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT difference(mean(\"electricity_used_tariff_1\"))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "electricity_delivered_tariff_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT difference(mean(\"electricity_used_tariff_1\"))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "electricity_delivered_tariff_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT (difference(mean(\"electricity_delivered_tariff_1\")) + difference(mean(\"electricity_delivered_tariff_2\")))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "electricity_used_tariff_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    }
   ]
  },
  {
   "title": "Daily electricity produced",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "solar",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "sma",
     "query": "SELECT difference(mean(\"electricity_used_tariff_1\"))  / 3600000 FROM \"power\" WHERE $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "ac_total_yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Amsterdam"
    }
   ]
  }
 ]
}