{
 "title": "System stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "node",
    "query": "label_values(node_boot_time_seconds, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{node_name=\"$node_name\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "I/O time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_io_time_seconds_total{node_name=\"$node_name\", device=~\"^[vsx]d[a-z]\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"^[vsx]d[a-z]\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"^[vsx]d[a-z]\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_bytes_total{node_name=\"$node_name\", device=~\"^(eno|enp|ens|eth|lan|wan|wlan).*$\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device=~\"^(eno|enp|ens|eth|lan|wan|wlan).*$\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  }
 ]
}