apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kibana
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.6.1
  values:
    elasticsearchHosts: 'http://elasticsearch-master.elasticsearch:9200'
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/whitelist-source-range: 82.197.204.61,94.103.16.181,217.114.100.73,217.114.98.148,172.21.40.0/21,2001:1540:802:6::/64
      hosts:
      - kibana.9ka.nl
      tls:
      - secretName: kibana-tls
        hosts:
        - kibana.9ka.nl
