apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kibana
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.5.2
  values:
    elasticsearchHosts: 'http://elasticsearch-master.elasticsearch:9200'
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/whitelist-source-range: 172.21.46.0/24,2001:1540:802:6::/64,82.197.194.78
      hosts:
      - kibana.9ka.nl
      tls:
      - secretName: kibana-tls
        hosts:
        - kibana.9ka.nl
