apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kibana
spec:
  releaseName: kibana
  helmVersion: v3
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.10.0
  values:
    elasticsearchHosts: 'http://elasticsearch-master.elasticsearch:9200'
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1500Mi
