apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: kibana
spec:
  encryptedData:
    values.yaml: AgCgnQD3s//1TuqNf2XbauxpebiQ++4HymxymQRd8a7u5mjE0IFjlL/I2/IFF/IppQxyUf+QzU3CVM8QzV6HtQGMwmHQPmJSvYNeRH7sRUcFYSuLNQFe8s4AkNesImHaRp/xA6IqPQ5unzRlKFUL929EaBg4gfDLuv65b5/8ZVKF0EcINfl//x421ZAW6tCdzwx3nmW1CU3OBoZSQeRhqjJVII+acTWWdpLZjWm/wRtZz3mf+OhlsTv3ApC6EzDl9rTkH51KK/NAi+4R814xXoz6C7/GVkaCLo7x1fksp53z9BHS+60pQyJ18s4eGeJrI9J35V7jTTen6pzyEQDwW9g70nhgTiYfdognHnCmycpq5ioXQcKbNv4Rxxfx0Veuk6UgxPITs5TJuYNS4JnUifKZnivljS1Tcc+1Nc4OTEgkf42+c73kH4SsHIBva4DY4/zDxE141+wxNukyo6zT8JWz/2U+7nrA0um445CqIbH0gANY8IO9dfd85eEpXur7Bdxz4kJhyUGN0MBt9pjWQORrPbiFZzqJ7qx2tn6JIJaD4idcD9OYqpWj35ujygYAdIasmsg8J5KHIRWy5pEsI+zOBB5c0LAnCrdEmJDWVM0hLuHPToTEEXq0dK0FwhHmD95COPyDzvaixjLUJMh5awY9J6VL1rvffmYjC7kvq54+nzYKysX5LSxCrqChJHh644fFJ6HXjDGT8s3fGwAUvN4mqor+FJXkUM0mqqJ5U/u7hmroxr3vdjv1eff4m5KkY6RsMks=
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: kibana
    type: Opaque
status: {}

