apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  helmVersion: v3
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.12.0
  values:
    controller:
      config:
        use-proxy-protocol: "true"
      extraArgs:
        enable-ssl-passthrough: ''
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: monitoring
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
        limits:
          cpu: 2
          memory: 500Mi
    defaultBackend:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 10m
          memory: 20Mi
