apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: lithium-node-exporter
  name: lithium-node-exporter
  namespace: monitoring
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: lithium-node-exporter
---
apiVersion: v1
kind: Endpoints
metadata:
  name: lithium-node-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 172.21.42.3
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lithium-node-exporter
  name: lithium-node-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: None
  type: ClusterIP
