apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alertmanager-gatekeeper
  namespace: monitoring
spec:
  releaseName: alertmanager-gatekeeper
  helmVersion: v3
  chart:
    repository: https://gabibbo97.github.io/charts/
    name: keycloak-gatekeeper
    version: 3.3.1
  values:
    ClientID: alertmanager
    discoveryURL: https://sso.9ka.nl/auth/realms/9ka
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
      - alertmanager.9ka.nl
      tls:
      - hosts:
        - alertmanager.9ka.nl
        secretName: alertmanager-tls
    upstreamURL: http://alertmanager-operated:9093/
  valuesFrom:
  - secretKeyRef:
      name: helm-gatekeeper-alertmanager
