apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCLwDpmeAaJ8VXvL4Bowxle3Pen/1jX/wCFaHcomXTcHIbjwLCHAwz/Sp1aahKdCGNAtSvnJupnqWr7xZ+8rhv8RAc3W8VvG40xyKFb5oVXym7xXM083e64FlFLXCt5OKMCdxVwH65XYctgdL+lgjVorz9V2/0QV/g2vHbnVY6QeGhMtrLT20aXbUx95C/D6/FuoM2Twxm9pjQn+o4JojiSYTcfZ3Rm3FSJqAIDiE7DOQSTuTFBs25v5j7C2zN/9adrelseStG72B7+asLb/fIJwJNJ2ZEc1Zo85QUdJtHWpS2ebTnSqx7wXqLeB8ndyWDitrbFA8s4Ekg4R5tQjPmdU16ABOLd9kuTmlpXlnXdf4wJwwftioY8OzcwYgM0xv0aDwkCaxeN7nXteAAkX48cEWYpAo+oCsgLT48rbwxDDHbHRuPgG0J8A/n2Pjcyxp8jkStBe/ujrc8DjN7+ytAlgeToQAJzGCZHNJgVTxMCv/tndKNuW2knpnGzW1Yhh+mKfh9/Y4YrwTXOvVHbY6WiTeStkko7XMQ3L8g/VOHqdaOPaadMAmjmDiUiyuYoB1P7jLf6o2L6D7OTqxoEq112fyYYz3wVHoLw0+SzUT3VGORcX3ED6Ofesm3ODN/HcqXQlJHYHvvHNhWqsrTR3DDy5x+tpUgiKsPNurrvSHEe8lCEXOE0KrQBxwvaeAQl0wDukSOFfcVbcVT6fsTfn+7aDpy7jHkX7FkGwIyJRqhNx4WuwPaTe1UTzXQKMHvPxOnLSSQ4oh0pneU0xtADIVg3mRUwAlizPRDurY+Ir+8NySPZCncaA4u35hDeR1Rn/3loZL47jf7s0+kqYH5QkhWq/7Wc1U3zV07LHqrsUcac2lDgCWnlXYq5/xIRduovNAMqrERNGks+urXHJW9UnV7n+W44gfkCQQQzbUpGwGQkNAiH2xBhX8pIrURiGekIQPJD9T/TaQmSy7albXsQS3A1C+q9s7Wf9uavx4ydKs2c63zh3vqmJhplI1Z05YyYM4eu97gHDJDJKl2XDTVbeALWBxSamdUYwNBbrxOIteEgXkk4UE0DWOzEZIJPRNfG3lvQgPfyWiRK4x52etDYRPO7J/NKN6ASMcdOp65C2oceoFxzETIyhrwPEF6nYW85x9GGcmf7QW8JKdPZu3O3j+5GGAmMtDpW0BVrWaOyJ5ILL6ST8XoMHVtzN4Y8aWa9bP+vEkfLRfjNx2u/ozDjnGsQzPLQMD3v4dhYTp5H+lhSTFFYga02rPfS0j+uEgiOddEnqU+Z0m7CsnAvJWTyMxbRu03kLi8wzRg9SrCSlLPxHG03aAWkmc7RSQ9/9nRGfBGb+cf4/1H+rlyJORtyQEZ7gL1KiAeKKAy7NXOUHSVKbLgfVAtlvWZNav0Z/FstHakxNctdwlZUZ4U0R642dMc+/pRHfDCdEotMy9WZVqKj9nTln24k/1U=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque

