apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgChLkwFxwg7/7ewSVksKnpRrux38E02ne6LVeCWOqBGPjfp1amjjIwrFgZ3DUYBWx+pfL8GMCElSdbhfDBhv2uejWR9Z080rDe67SnqJUJtJJytSb5M04lyeesGmOar8s4ImUBtP7roD8bdwQoa2J5PLkibimJ50tZ2VPuxSyBrpzkqFTxgybaMGxvARSNOY3gZdyWiOjw9E4lfg7IMiDCDDt6PgZAGcuiD68nFeWJyt+GLbT+WwOoh6G1dvI6Ep5M7VdVDPdiKmMJsVpt1tpARUUO5lPRqLuUS6lu2VfuaDIFt5naSlbIo4mIfqhT6I5aNhSaz35/zxYi5oFK2OGhi+hZ+1cuv6UZL5L/KA5hflZgKMFyGxD0hYigicZhzJzqcLMVn+AaWW5Vje+oiocwWZPMFQR5r/7vhqASy0HASdD30+xjk71pk/nConhhgJF5Gj6Ai+e8BopvlcrETITr6/F0FuN0mbAlzEso2SNig3UcGef9lsybqgyPtqe3UjEZZG5l3WI6RFwjnaditXUyD3z4Jtg//ier+vAS93JaCg/kS/0oihHVBbf/by1jNRbB6TDeQywlvgSzPsj6ugR0AXxWvGFkazBXdV2ncxy6cvWChUi5QNU3LZ6Wk4XOqZlLoUsiiVyyaaFvXAl3mbjzXa+3l+sI8IyYfJTz9W5gdmiiam2Gdqab8VOiqkuuZ8FhVCVnCC5KBoPeyhpJ4ZEwBeq7P3FwIIk3rf9V2U7p3xcAoO1pQjQceLdnnK8eC6O0KRGcc2esaOuSwjI8T3pW+EShq2+1/smcEVri2rCdgpUUi1GQLLNMAUsdlVta5unKLyl+J675ca5qPPy+OsXvcrQvVmiGAWWCjMtxpb184gq6HIODEx5no9bavk8m99gkAk1yAQStnD00DLMru3skRrF2JX5OlrD3omkiFYr9cL4/OUQJSqzrlHPHjeDyPIzYiQFQuyAajz+wkeY2g20e/C23A819pcf12Fg59QyntAI7RREx9atDF20Ir2I5ox507qftSf/+GjpvFH4KPmay7ZQdISpf7GKScZc2YOhLS1eySSmhNQ4n5tWf7a4xT/6mPNdh6iq0DiKmcGgw8YDtUZP0ksGZNttH3d1lRBSnSGNpoM88cFRPPXFB6mh5m6+9chzaxtkafUthHaOluaqzbAkhdF3CK9pS4b/wGdtp/aguxAvT1Z6xLohS7AmSOfJG/KPlAiMfKG+4Bf+mmwoPEb78wHNI6sl8OMxMlwwuwUaanrV3WqipSgvo2+ACY5Eg7HkYqXrAyV8dxqxjk6hmjSeHP+deYp9iDcuF6xhGmqcauAgRS6BNPIZwYgJLX713+fiMbnx2fizadI6HIiGKYqFeHkGdKa4wL7NXnycrTorAEpsFgRhqJaYIJQVD2jNDw1HBGG4BJ0A==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
status: {}

