apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCvjxMyEwSi7oOKSHLeF2pHiuUmzDCKZhZ3CDVX+Y9fIDgNHdeiQnUEIFQiyLFRIWOwTjgjSqf/K9mdfcJ7y6/DOuu+ayvDApYu88COZsRSGZJhwNQsfp1dLPIqbSBI74IekKWLqbsYQkNIdaJnev+185VW1hXJ08DmzP3kXNbbMp+1kfYD+HjCHWSOz3ly33r0xpBdwnfTula2tbl0hGKWKwW1H6UjCzxRwaTwjGxl9qt0iytmLmu26wMCLMtT9f//5GSQziYE9k3Xo0CT5uFI9nxADXTEzdDElH314qSkmdRTxlmMlWex3ALCxhsSbNAC4uKylLIKjUGAv4QDZZ6WGKwVboyC7RVUqK2I/yFBmzdZs+S2BTJBsLC6NyLApH9KJk0r3W5f9Rfy2zneUcx4VX3UL5lFv+kVVESZafNY4mVvOC03XpoD6z8lQSyVysGSOhZnDN/VnEYc/YKwoG9M9NIs5Yj2JtRPU4d3RrPqlGxbPOVhoqAOGsiTmBRuWnB1sI6Xs/7nC/xXQG365gq1M29gbRs8IutQ8ZlaSNb0bxJuDtWAv4NZ/DwFOqzKk0qSEDT49EgSHJwbx0W/XKICRqUK4QXPMbdQo/t0ALhvdPa6MZteCX2qUSQpoLIQ5enqJs9C+cD9nwa0vvN6RkuCpA5nnhl15N//PmqjJwNZGkT9ApOZOjYqufPEg2iHbenZIW+BND1MwkB95V4KdJjthWMx8xEmsuLP/4yjmZ8W+uOcjgZ01qbKBIySFaOMdObComjDTgH2i0IQobOA/HXDwPzsUxDXyFt7mYuor/yuXo6t6n5/VDQ+QJGIiYGVmu/amvuUDYMMovrnTeh1fyLb+pKMjmZjhK7eOwrm+wtDKc+bsSe5G247i6T0qfMyE6GJIDxdn4pwAk/y+OEWfKZOcbxIqaBXhsha4yZhlcDs0z6KQ8/7IJ50F3ACHtVbrJDUGtigZjdzcZcR/yLP8gKFxUuPBt/e/D0/N53c+i6rwAS7GCVeIZ6y1dvLBaPPwkpe+o9Yxh5JKaqkMU6iXWUDWqbP3Y9GyS99eMPH37kLq+asbSYumXnJ0Z1oAbiLrfEkM9VwzQ+YbYJBVlhoJxyHJOHacx2QFi/qqXwC5Nu91ufL0LWWv57uIc7BGyBUCy1/U5ulbmsX3pLS1CTPxYsXxaxpyQ6/qXKx4yzqS20Yig==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
status: {}

