apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAiM3bGBxEQWdewm3lqmdUJkgbp5FSRbPln9LXZNB4DbMYwFiRF7r7SxWVOwEMcwkfHx3btiwAYY2Z/PZHiJez+fOm5L3ohXbzZgPngBSe5mxQJjV4t3OGoCqP/BqHXDfp7wuTfbedK/H09ctE99faCHvb1QTh/KWaT2Vo24kWH2fJd5OQyaBZ4PqsUmDpFI4Cro1NIxq+SaOMZ31U8y/afiYABkJZebpx+j4nSjoexQJBryubs2JE37e3uhE0SANpCOi3y6I33ufeOWMaw27451VjD/eKP3W7eP7w6KWbzgTQtqaKN3lQPjTi9vWkZ4wMGMM+HmjsmFGOkBpPewGfTl4dkf+dicV/E254g14+zwwzq6K2T2XT/ethPpbuxi0OG5nK6D85m67rDrpUNbF3RuWfnc/lEebZaJNir4LBo4S5tO4+sGTow0pY872o92R/bsiY+wredbOIO+Hty0GUzdWYeBOHSY+uRf5LwjRPEH+OfdJrhA+b/VMy6YTp+cSINA/8+BWBp/AZflfLj9zcNd7+Y3zDJ6rGA1Qx5xXKwM3s4mZCd0MuBvuJCnVxzhFyos6Mw+akZONxrUpiQoM7EeMr/5947YbdEH6PcCmxdDmFXUZoJdDlXl1oZ8w9kT5P54yCJbpOp75CNfYALvEd0RXCOd9ZtYbWu9A1GumXq7m4RV0v/wm918ZZsYjOV4yjb1ECgBEzYqPYCA5cB/4ue1ZDQgGO5W6ZNu180V2IHMLoyCMCchx0IHKTE8M5W2JNqAs5mIQctz1rJgedYw5lAfeTflREUfL55nsX9p2ludr4Oi9KF7ECNM5g/6LmkERQYPPoc5nWxLF3jsBHuAJ00DgyicbuWMTfWcLC3k6LbRxSrYaRnMqz7TREczqNoUlXMpkHORTfY07JaApT4k/nGanug5RN5rQyCpEklnfhblk1DM+kXuHCrmGPJrQox6+m37fDLsLaTPcHFRaENpkSLAR89f1BX2u5XVyTeOmJx2Vzi731YpckrtTIBZJLn4rWUnttbvKUWHwPhZWqRde/l2Junj2hxbeO7XVcz0w2k3siv5OaC7A+kU03B12g/pN3z0YJSPWzispwKf5dLuKjHQJotOvuDGoPN2r1JhBV0DX7S8qchm3PqnubKz86FaWMA/dCjkvFxGFzXqd/umwROf/L5rreB+HQJRsZIXjZ8bUNhtsoyOFMqy1Cp
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
status: {}

