apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  helmVersion: v3
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 9.9.1
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      rules:
      - host: sso.9ka.nl
        paths:
        - /
      tls:
      - secretName: keycloak-tls
        hosts:
        - sso.9ka.nl
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    pgchecker:
      resources:
        limits:
          cpu: "10m"
          memory: "32Mi"
    postgresql:
      enabled: true
      existingSecret: keycloak-postgresql
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
