apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 7.2.0
  values:
    keycloak:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        enabled: true
        hosts:
        - sso.9ka.nl
        tls:
        - secretName: keycloak-tls
          hosts:
          - sso.9ka.nl
      persistence:
        deployPostgres: true
        dbVendor: postgres
    postgresql:
      persistence:
        enabled: true
    prometheus:
      operator:
        enabled: true
