apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  helmVersion: v3
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 9.1.0
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      rules:
      - host: sso.9ka.nl
        paths:
        - /
      tls:
      - secretName: keycloak-tls
        hosts:
        - sso.9ka.nl
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    postgresql:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
      interval: 60s
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
  valuesFrom:
  - secretKeyRef:
      name: helm-secrets
