apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 9.0.1
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      rules:
      - host: sso.9ka.nl
        paths:
        - /
      tls:
      - secretName: keycloak-tls
        hosts:
        - sso.9ka.nl
    extraEnv:
    - key: PROXY_ADDRESS_FORWARDING
      value: "true"
    postgresql:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: monitoring
      interval: 60s
  valuesFrom:
  - secretKeyRef:
      name: helm-secrets
