apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBQ+Jh5d25J16jONmvhYjsTPup+3dn6TW/Z2pwWw9IWX+mqKcldAugFZARTImfQFMotnaLz2XP58eTBXxnJxyDOk8ksbcARgn1Lcd9cPv7xXfd1GNuUy59ApTjb/9E9xJLTUenL9vxGqqsoNaamuU69CKUuSPiZxYSeQVu0+4fyqkY1MV388pWcRgztDVQrvJJnesw8LsOUcwXp+YMScHkvUwq24I1lUnhCxMRVfbI+NsF7wdkVkFD7BblDzyFEEe7qojwGF/jIj6sos/6AZhFgY8g4E4HIZdhzE43SrDSyRi1uXvL/anuoPjY55Y36BucHdH0P8cVaHX+wnj3dQQX/SM5P5ed6EtFD0jtPI0ykNd+Y6UlPPt2BdO9Q5a7bLE4ZlYygFemM5duynoya5plOYB2pNa3wW/FxTuNEZQn6oPdREZ2PsbKWDsh5evnc8pu+iP8T/7UTlxVVWp+ghpHaYgS67jNFXJuXz77s+QwA/NopUYfe1LOEycQTuyIiqF6FX7Io8dBuftSayddS/G75DkiC1B/+M5TpSZrTB75ECMTch8LAOc17NqqMYOVd3YAd5tSSiXd4RsrR9EJqTRgvXk1qh4qjFCGpuBk/5YIZUv+CkmdPBcFzZF+eFlmYq3UQsNhLsYOcYI6PG1RZKnr9VYZKnwK2zAiv/Mx8mJHVs78LmETF8kAljW3ACk1YSrlsGSL5+rXXUmjRcDc+VQ==
    postgresql-postgres-password: AgCE5O0DA09plSlEQUPS4u5jCqFn1RnRgqeUTc/u5vOMat7WOrLm2a2TyJIp54hu6k5Yh+a44XD24AeG1r/qGSS4C8/StfcfnYpSclLmSZ8REzAnUfB2LU0X1HIaO5kcOOcG1HC48ssKc6+idrHm1zuCfhKra08TCfkC9aEYvYnr/4phjbhBosodDp18dT3w1QHUpu4nqa1akpf36HQfXqmxj57T6S9ktUqCWlN28iMWeO4B6p7SzfEZn9MB7hInT4k+QB/dTI/+wYsYQK5cd2+vwxARQ1Rl3yA8dSs0QCCMU1rSCoOof9o/4RBdPKVXLd6QAm4U7XutyR8P/ntDZl1DEDid1E3nlkmLMNKhvecdBD7SOjskiK0cosYJMCukQS3JleaEwkT1q8jVZ9A+pycL8kQbZmzkSZUZMDeuuoPgQ6TBmQIPGMv3VcIvMBgGdYLvItQV83BZveSpcGgxONXayuFjEgaLVcTnpBHuk12Ns5kqkaNAuNL6iXY3HneZQa1+LroewfmDrVcUzV2WnxK2NQJj9owAFaeqHqKhUgY9cO+JoK565qfIX4v+7Uzsnd6wIbwyp2PqAp1l0PnJoI3HRtIs7/Qqdrmg3YIjPKo/0bHiIuPcCiW3vXHrxdxaINN2GOy0WpV7kY6OTNVhF8xq9Wt4NlFmXYRu/JiFQH/ir+KzNX7HB7CHeat9KUFrJkYF0Iuhdvmf7gxbBAWPy4Qa
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

