apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  helmVersion: v3
  chart:
    repository: https://charts.helm.sh/stable
    name: sealed-secrets
    version: 1.12.2
