apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bitwarden-rs
  namespace: bitwarden-rs
  annotations:
    helm.fluxcd.io/migrate: "true"
spec:
  releaseName: bitwarden-rs
  helmVersion: v3
  chart:
    repository: https://skeen.github.io/helm-bitwarden_rs
    name: bitwarden
    version: 0.2.0
  values:
    bitwarden:
      domain: https://brs.9ka.nl
      invitations_allowed: true
      server_admin_email: jorik@efgh.nl
      signups_allowed: false
      smtp_from: jorik@efgh.nl
      smtp_host: 172.21.46.1
      smtp_port: 25
      smtp_ssl: false
    deployment:
      image:
        tag: 1.16.3
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - brs.9ka.nl
      paths:
      - /
      tls:
      - secretName: bitwarden-tls
        hosts:
        - brs.9ka.nl
