apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  releaseName: elasticsearch
  chart:
    repository: https://helm.elastic.co
    name: elasticsearch
    version: 7.6.0
  values:
    ingress:
      enabled: true
      hosts:
      - elastic.9ka.nl
      tls:
      - secretName: elastic-tls
        hosts:
        - elastic.9ka.nl
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/whitelist-source-range: 172.21.46.0/24,2001:1540:802:6::/64,82.197.194.78
