apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zfs
  namespace: monitoring
spec:
  groups:
  - name: zfs
    rules:
    - alert: ZFSPoolNotOnline
      annotations:
        message: 'ZFS Pool {{ $labels.pool }} on {{ $labels.node_name }} is not online'
      expr: node_zfsstatus > 0
      labels:
        severity: critical
