apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  releaseName: promtail
  chart:
    repository: https://grafana.github.io/loki/charts
    name: promtail
    version: 0.19.2
  values:
    loki:
      serviceName: loki.loki
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
