apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  releaseName: influxdb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: influxdb
    version: 4.2.3
  values:
    config:
      http:
        auth_enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hostname: influxdb.9ka.nl
      tls: true
      secretName: influxdb-tls
    persistence:
      enabled: true
      storageClass: ssd
    setDefaultUser:
      enabled: true
