apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  releaseName: influxdb
  helmVersion: v3
  chart:
    repository: https://helm.influxdata.com/
    name: influxdb
    version: 4.9.13
  values:
    config:
      http:
        auth-enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: null
      enabled: true
      hostname: influxdb.9ka.nl
      tls: true
      secretName: influxdb-tls
    persistence:
      enabled: true
      storageClass: ssd
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 2
        memory: 1Gi
