apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  releaseName: influxdb
  chart:
    repository: https://helm.influxdata.com/
    name: influxdb
    version: 4.7.0
  values:
    config:
      http:
        auth-enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hostname: influxdb.9ka.nl
      tls: true
      secretName: influxdb-tls
    persistence:
      enabled: true
      storageClass: ssd
