apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  helmVersion: v3
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.1
  values:
    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: monitoring
